#ifndef FIGHTER_GLOBAL_CONFIG_H
#define FIGHTER_GLOBAL_CONFIG_H

#define FIGHTER_COORDINATE_NUMBER 4
#define FIGHTER_COORDINATE_1_X 30
#define FIGHTER_COORDINATE_1_Y 50
#define FIGHTER_COORDINATE_2_X 0
#define FIGHTER_COORDINATE_2_Y 60
#define FIGHTER_COORDINATE_3_X 30
#define FIGHTER_COORDINATE_3_Y 0
#define FIGHTER_COORDINATE_4_Y 60
#define FIGHTER_COORDINATE_4_X 60

#define FIGHTER_ENEMY 1
#define FIGHTER_PLAYER 0

#define FIGHTER_HP_MAX 100
#define FIGHTER_CREATE_SHELL_CORRECTED_VALUE_X 25

#define FIGHTER_PLAYER_FILL_COLOR sf::Color::Magenta
#define FIGHTER_PLAYER_OUTLINE_COLOR sf::Color::Red
#endif
