#ifndef FIGHTER_GLOBAL_CONFIG_H
#define FIGHTER_GLOBAL_CONFIG_H

#define FIGHTER_COORDINATE_NUMBER 4
#define FIGHTER_COORDINATE_1_X 30
#define FIGHTER_COORDINATE_1_Y 50
#define FIGHTER_COORDINATE_2_X 0
#define FIGHTER_COORDINATE_2_Y 60
#define FIGHTER_COORDINATE_3_X 30
#define FIGHTER_COORDINATE_3_Y 0
#define FIGHTER_COORDINATE_4_Y 60
#define FIGHTER_COORDINATE_4_X 60

#define FIGHTER_ENEMY 1
#define FIGHTER_PLAYER 0
#endif
