#ifndef SHELL_GLOBAL_CONFIG_H
#define SHELL_GLOBAL_CONFIG_H

#define SHELL_CIRCLE_RADIUS 5
#define SHELL_FILL_COLOR Red
#define SHELL_ORIGIN_COORDINATE_X SHELL_CIRCLE_RADIUS
#define SHELL_ORIGIN_COORDINATE_Y SHELL_CIRCLE_RADIUS

#endif
